In [3]:
import numpy as np
from sklearn.neighbors import NearestNeighbors 
sample = [[0,0,2],[1,0,0],[0,0,1]]

In [9]:
neigh = NearestNeighbors(2,0.4)
neigh.fit(sample)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=1, n_neighbors=2, p=2, radius=0.4)

In [10]:
neigh.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': 1,
 'n_neighbors': 2,
 'p': 2,
 'radius': 0.4}

In [15]:
distance,indices = neigh.kneighbors([[0,0,1.3]],2,return_distance=True)

In [16]:
distance

array([[0.3, 0.7]])

In [17]:
indices

array([[2, 0]])

In [20]:
neigh.kneighbors_graph([[0,0,1.3]]).toarray()

array([[1., 0., 1.]])

In [22]:

A = [[8,1,6],[3,5,7],[4,9,2]]
evals,evecs = np.linalg.eig(A)
print(evals)
print(evecs)

[15.          4.89897949 -4.89897949]
[[-0.57735027 -0.81305253 -0.34164801]
 [-0.57735027  0.47140452 -0.47140452]
 [-0.57735027  0.34164801  0.81305253]]
